### ISSUE TITLE
List index out of range on Highscore object instantiation

### ISSUE THREAD

**Issue by kcsparks** [matthew-palmer/osrs_highscores#7]
Greetings,

I am trying to instantiate a Highscore object and am receiving a list index out of range error. Below are all of the code samples that fail.

`highscore_obj = Highscores("CrimBlue")`
`highscore_obj = Highscores("All Father")`
`highscore_obj = Highscores("A Snorelax")`

Here is the error:
```
Traceback (most recent call last):
  File "/Users/kcsparks/repos/project1/env/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/kcsparks/repos/project1/p/plugins/OsrsPlugin.py", line 12, in hello
    highscore_obj = Highscores("CrimBlue")
  File "/Users/kcsparks/repos/project1/env/lib/python3.7/site-packages/osrs_highscores/highscores.py", line 30, in __init__
    self.__instantiate()
  File "/Users/kcsparks/repos/project1/env/lib/python3.7/site-packages/osrs_highscores/highscores.py", line 100, in __instantiate
    self.__process_data()
  File "/Users/kcsparks/repos/project1/env/lib/python3.7/site-packages/osrs_highscores/highscores.py", line 63, in __process_data
    'level': data[1],
IndexError: list index out of range```

Thanks for taking a look!

**Comment by kcsparks** [comment]
This was due to an error being displayed by the osrs site that is not being accounted for in the code. After the site was back up I was unable to repro this issue.

**Comment by matthew-palmer** [comment]
I think this is a perfect case to enhance the error handling as the highscores have been unstable. I think adding a proper test case and handling is required in situations where this occurs; Adding a back off retry could also help.

**Comment by matthew-palmer** [comment]
Merged GH-8, new release cut for fix pending acceptance testing of api

**Comment by matthew-palmer** [comment]
While this is expected, I have adjusted the logic which will error on a retry loop returning no data. This will still happen if the highscores are unresponsive or down, but should be less so, and give a more informed response over a stacktrace dump.
